# Generated by Django 4.2 on 2023-04-12 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('dni', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(default='sin_nombre', max_length=250)),
                ('carrera', models.CharField(default='sin_carrera', max_length=5)),
            ],
        ),
    ]
