# Generated by Django 4.2 on 2023-05-05 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('dni', models.IntegerField(primary_key=True, serialize=False)),
                ('apellido', models.CharField(default='sin_apellido', max_length=250)),
                ('nombre', models.CharField(default='sin_nombre', max_length=250)),
                ('carrera', models.CharField(default='sin_carrera', max_length=30)),
            ],
        ),
    ]
