# Generated by Django 4.2 on 2023-05-11 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscriptos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='email',
            field=models.CharField(default='-', max_length=100),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='apellido',
            field=models.TextField(default='-', max_length=250),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='carrera',
            field=models.CharField(default='-', max_length=30),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='nombre',
            field=models.TextField(default='-', max_length=250),
        ),
    ]
